# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest5():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test5(self):
    # Test name: Test 5
    # Step # | name | target | value
    # 1 | open | https://www.idx.co.id/id/perusahaan-tercatat/laporan-keuangan-dan-tahunan | 
    self.driver.get("https://www.idx.co.id/id/perusahaan-tercatat/laporan-keuangan-dan-tahunan")
    # 2 | setWindowSize | 965x861 | 
    self.driver.set_window_size(965, 861)
    # 3 | click | css=.bzg_c:nth-child(3) > .mb-8:nth-child(3) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(3) > .mb-8:nth-child(3) span").click()
    # 4 | click | css=.bzg_c:nth-child(4) > .mb-8:nth-child(5) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(4) > .mb-8:nth-child(5) span").click()
    # 5 | click | css=.btn--wider:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn--wider:nth-child(2)").click()
    # 6 | mouseOver | css=.main-nav__item:nth-child(3) .menu-cluster:nth-child(5) > a | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".main-nav__item:nth-child(3) .menu-cluster:nth-child(5) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 7 | mouseOut | css=.main-nav__item:nth-child(3) .menu-cluster:nth-child(5) > a | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 8 | click | css=.site-main | 
    self.driver.find_element(By.CSS_SELECTOR, ".site-main").click()
    # 9 | waitForElementPresent | css=.bzg_c:nth-child(1) .box-title | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".bzg_c:nth-child(1) .box-title")))
    # 10 | click | css=.bzg_c:nth-child(3) > .mb-8:nth-child(4) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(3) > .mb-8:nth-child(4) span").click()
    # 11 | click | css=.bzg_c:nth-child(4) > .mb-8:nth-child(5) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(4) > .mb-8:nth-child(5) span").click()
    # 12 | click | css=.bzg_c:nth-child(3) > .mb-8:nth-child(3) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(3) > .mb-8:nth-child(3) span").click()
    # 13 | click | css=.btn--wider:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn--wider:nth-child(2)").click()
    # 14 | click | css=.bzg_c:nth-child(1) small | 
    self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(1) small").click()
    # 15 | storeText | css=.bzg_c:nth-child(1) small | Date
    self.vars["Date"] = self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(1) small").text
    # 16 | click | css=.bzg_c:nth-child(1) tr:nth-child(2) > .full-width | 
    self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(1) tr:nth-child(2) > .full-width").click()
    # 17 | storeText | css=.bzg_c:nth-child(1) tr:nth-child(2) > .full-width | Tahun_buku
    self.vars["Tahun_buku"] = self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(1) tr:nth-child(2) > .full-width").text
    # 18 | click | css=.bzg_c:nth-child(1) .table tr:nth-child(2) > td:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(1) .table tr:nth-child(2) > td:nth-child(1)").click()
    # 19 | click | css=.bzg_c:nth-child(1) tr:nth-child(2) .bzi-download | 
    self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(1) tr:nth-child(2) .bzi-download").click()
    # 20 | click | css=.bzg_c:nth-child(1) tr:nth-child(2) .bzi-download | 
    self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(1) tr:nth-child(2) .bzi-download").click()
    # 21 | doubleClick | css=.bzg_c:nth-child(1) tr:nth-child(2) .bzi-download | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(1) tr:nth-child(2) .bzi-download")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 22 | click | css=.bzg_c:nth-child(1) tr:nth-child(2) .bzi-download | 
    self.driver.find_element(By.CSS_SELECTOR, ".bzg_c:nth-child(1) tr:nth-child(2) .bzi-download").click()
    # 23 | click | css=.btn-arrow > .bzi-angle-right | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-arrow > .bzi-angle-right").click()
    # 24 | runScript | window.scrollTo(0,3256) | 
    self.driver.execute_script("window.scrollTo(0,3256)")
    # 25 | click | css=.btn-arrow > .bzi-angle-right | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-arrow > .bzi-angle-right").click()
    # 26 | click | css=.\--next | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\--next").click()
    # 27 | click | css=.\--next | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\--next").click()
    # 28 | runScript | window.scrollTo(0,2872) | 
    self.driver.execute_script("window.scrollTo(0,2872)")
    # 29 | click | css=.\--next | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\--next").click()
    # 30 | click | css=.\--next | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\--next").click()
    # 31 | runScript | window.scrollTo(0,2744) | 
    self.driver.execute_script("window.scrollTo(0,2744)")
    # 32 | click | css=.\--next | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\--next").click()
    # 33 | runScript | window.scrollTo(0,2877) | 
    self.driver.execute_script("window.scrollTo(0,2877)")
    # 34 | click | css=.\--next | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\--next").click()
  
