from Script.General import *
from multiprocessing import Pool
g = General()


register = [
    ['kas','2','CurrentYearInstant','Kas dan setara kas'],
    ['kas','2','CurrentYearInstant','Kas'],  
    ['jumlah_aset_lancar','2','CurrentYearInstant','Jumlah aset lancar'],
    ['jumlah_aset_lancar','2','CurrentYearInstant',['Kas dan setara kas',
                                                    'Piutang hasil investasi',
                                                    'Piutang premi',
                                                    'Piutang reasuransi',
                                                    'Piutang lainnya',
                                                    'Aset reasuransi',
                                                    'Investasi dalam deposito berjangka',
                                                    'Investasi pada efek dan reksadana yang diukur pada nilai wajar melalui laba rugi',
                                                    'Investasi pada efek yang tersedia untuk dijual',
                                                    'Penyertaan saham',
                                                    'Biaya dibayar dimuka',
                                                    'Biaya dibayar dimuka',
                                                    'Aset pajak tangguhan']],
    ['jumlah_aset_lancar','2','CurrentYearInstant',['Kas',
                                                    'Giro pada bank indonesia',
                                                    'Giro pada bank lain pihak ketiga',
                                                    'Giro pada bank lain pihak berelasi',
                                                    'Cadangan kerugian penurunan nilai pada giro pada bank lain',
                                                    'Penempatan pada bank indonesia dan bank lain pihak ketiga',
                                                    'Penempatan pada bank indonesia dan bank lain pihak berelasi',
                                                    'Cadangan kerugian penurunan nilai pada penempatan pada bank lain',
                                                    'Efek-efek yang diperdagangkan pihak ketiga',
                                                    'Efek-efek yang diperdagangkan pihak berelasi',
                                                    'Cadangan kerugian penurunan nilai pada efek-efek yang diperdagangkan',
                                                    'Wesel ekspor dan tagihan lainnya pihak ketig',
                                                    'Cadangan kerugian penurunan nilai pada wesel ekspor dan tagihan lainnya',
                                                    'Tagihan akseptasi pihak ketiga',
                                                    'Tagihan derivatif pihak berelasi',
                                                    'Pinjaman yang diberikan pihak ketiga',
                                                    'Pinjaman yang diberikan pihak berelasi',
                                                    'Cadangan kerugian penurunan nilai pada pinjaman yang diberikan',
                                                    'Aset keuangan lainnya',
                                                    'Biaya dibayar dimuka',
                                                    'Aset pajak tangguhan']],
    ['persediaan','2','CurrentYearInstant','Persediaan lancar lainnya'],
    ['persediaan','2','CurrentYearInstant',['Investasi pada efek yang tersedia untuk dijual',
                                            'Penyertaan saham']],
    ['persediaan','2','CurrentYearInstant',['Efek-efek yang diperdagangkan pihak ketiga',
                                            'Efek-efek yang diperdagangkan pihak berelasi']],                                        
    ['piutang','2','CurrentYearInstant',['Piutang usaha pihak ketiga',
                                         'Piutang usaha pihak berelasi']],
    ['piutang','2','CurrentYearInstant',['Piutang hasil investasi',
                                         'Piutang premi',
                                         'Piutang reasuransi',
                                         'Piutang lainnya']],
    ['piutang','2','CurrentYearInstant',['Wesel ekspor dan tagihan lainnya pihak ketiga',
                                         'Cadangan kerugian penurunan nilai pada wesel ekspor dan tagihan lainnya',
                                         'Tagihan akseptasi pihak ketiga',
                                         'Tagihan derivatif pihak berelasi',
                                         'Pinjaman yang diberikan pihak ketiga',
                                         'Pinjaman yang diberikan pihak berelasi']],
    ['jumlah_aset_tidak_lancar','2','CurrentYearInstant','Jumlah aset tidak lancar'],
    ['jumlah_aset_tidak_lancar','2','CurrentYearInstant',['Properti investasi',
                                                          'Aset tetap',
                                                          'Aset lainnya']],
    ['jumlah_aset_tidak_lancar','2','CurrentYearInstant',['Aset tetap',
                                                          'Agunan yang diambil alih',
                                                          'Aset lainnya']],
    ['jumlah_aset','2','CurrentYearInstant','Jumlah aset'],
    ['jumlah_liabilitas_jangka_pendek','2','CurrentYearInstant','Jumlah liabilitas jangka pendek'],
    ['jumlah_liabilitas_jangka_pendek','2','CurrentYearInstant',['Utang reasuransi',
                                                                 'Utang komisi',
                                                                 'Utang klaim',
                                                                 'Utang pajak']],
    ['jumlah_liabilitas_jangka_pendek','2','CurrentYearInstant',['Liabilitas segera',
                                                                 'Giro pihak ketiga',
                                                                 'Giro pihak berelasi',
                                                                 'Tabungan pihak ketiga',
                                                                 'Tabungan pihak berelasi',
                                                                 'Deposito berjangka pihak ketiga',
                                                                 'Deposito berjangka pihak berelasi',
                                                                 'Simpanan dari bank lain',
                                                                 'Liabilitas derivatif pihak berelasi',
                                                                 'Liabilitas akseptasi',
                                                                 'Pinjaman yang diterima pihak ketiga',
                                                                 'Obligasi',
                                                                 'Estimasi kerugian komitmen dan kontinjensi',
                                                                 'Utang pajak']],                                                        
    ['jumlah_liabilitas_jangka_panjang','2','CurrentYearInstant','Jumlah liabilitas jangka panjang'],
    ['jumlah_liabilitas_jangka_panjang','2','CurrentYearInstant',['Liabilitas asuransi atas premi yang belum merupakan pendapatan',
                                                                  'Liabilitas asuransi atas estimasi liabilitas klaim',
                                                                  'Kewajiban imbalan pasca kerja',
                                                                  'Liabilitas lainnya']],
    ['jumlah_liabilitas_jangka_panjang','2','CurrentYearInstant',['Liabilitas lainnya',
                                                                  'Kewajiban imbalan pasca kerja']],                                                              
    ['jumlah_ekuitas','2','CurrentYearInstant','Jumlah ekuitas'],
    ['jumlah_liabilitas','2','CurrentYearInstant','Jumlah liabilitas'],
    ['jumlah_ekuitas','2','CurrentYearInstant','Jumlah ekuitas'],
    ['pendapatan','3','CurrentYearDuration','Penjualan dan pendapatan usaha'],
    ['pendapatan','3','CurrentYearDuration','Pendapatan dari premi asuransi'],
    ['pendapatan','3','CurrentYearDuration','Pendapatan bunga'],
    ['pendapatan','3','CurrentYearDuration',['Pendapatan bunga dan keuangan',
                                             'Pendapatan dari murabahah dan istishna',
                                             'Pendapatan dari pembiayaan konsumen',
                                             'Pendapatan dari sewa pembiayaan',
                                             'Pendapatan administrasi',
                                             'Pendapatan dari provisi dan komisi',
                                             'Pendapatan dividen',
                                             'Penerimaan kembali aset yang telah dihapusbukukan',
                                             'Keuntungan (kerugian) selisih kurs mata uang asing',
                                             'Keuntungan (kerugian) pelepasan aset tetap']],
    ['cogs','3','CurrentYearDuration','Beban pokok penjualan dan pendapatan'],
    ['cogs','3','CurrentYearDuration',['Beban bunga','Beban bagi hasil',
                                       'Beban keuangan',
                                       'Pembentukan penyisihan kerugian penurunan nilai',
                                       'Beban penjualan',
                                       'Beban penjualan',
                                       'Beban penjualan',
                                       'Beban umum dan administrasi',
                                       'Beban penyusutan properti investasi, aset sewa, aset tetap, aset yang diambil alih dan aset ijarah']],
    ['cogs','3','CurrentYearDuration',['Beban klaim',
                                       'Klaim reasuransi',
                                       'Klaim reasuransi',
                                       'Klaim reasuransi',
                                       'Beban underwriting lainnya',
                                       'Beban umum dan administrasi']],
    ['laba_bruto','3','CurrentYearDuration','Jumlah laba bruto'],
    ['laba_bruto','3','CurrentYearDuration','Jumlah laba (rugi) sebelum pajak penghasilan'],
    ['laba_rugi','3','CurrentYearDuration','Jumlah laba (rugi)'],
    ['laba_rugi_komprehensif','3','CurrentYearDuration','Jumlah laba rugi komprehensif'],
    ['EPS','3','CurrentYearDuration','Laba (rugi) per saham dasar dari operasi yang dilanjutkan'],
]